
export enum ChangePlanViewActions {
  RESET_CODE_CHAT_STORE = "RESET_CODE_CHAT_STORE",
  SET_CHANGE_DESCRIPTION = "SET_CHANGE_DESCRIPTION",
  SET_IS_LOADING = "SET_IS_LOADING",
  SET_LLM_RESPONSE = "SET_LLM_RESPONSE",
  SET_CURRENT_STEP = "SET_CURRENT_STEP",
}
